package scenarios.common.wa

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import utilities.DateUtils
import utils.{Environment, Headers}

object LiveReportingJourney {

	val userFeeder = csv("WA_LiveReportingUsers.csv").circular
	val serviceFeeder = csv("WA_LiveReportingServices.csv").random
	val regionFeeder = csv("WA_LiveReportingRegions.csv").random
	val roleFeeder = csv("WA_LiveReportingRoleCategories.csv").random

	val HomePage = {

		exec(http("WALiveReporting_010_HomePage")
			.get(Environment.waLiveReportingUrl)
			.headers(Headers.WALiveReportingHeader)
			.check(css("input[name='_csrf']", "value").saveAs("csrf"))
			.check(headerRegex("Set-Cookie", "x-csrf-token=(.+?);").saveAs("snapshotToken")))

		.pause(Environment.constantthinkTime)
	}

	val Login = {

		feed(userFeeder)

		.exec(http("WALiveReporting_020_Login_EnterEmail")
			.post(Environment.hmctsAccessUrl + "/enter-email")
			.headers(Headers.WALiveReportingHeader)
			.formParam("email", "#{email}")
			.formParam("_csrf", "#{csrf}"))

		.exec(http("WALiveReporting_020_Login_EnterPassword")
			.post(Environment.hmctsAccessUrl + "/enter-password")
			.headers(Headers.WALiveReportingHeader)
			.formParam("action", "_submit")
			.formParam("password", "#{password}")
			.formParam("_csrf", "#{csrf}")
			.check(css("input[name='_csrf']", "value").saveAs("csrf")))

		.pause(Environment.constantthinkTime)
	}

	val Overview = {

		group("WALiveReporting_030_Overview") {
			exec(http("Overview")
				.post(Environment.waLiveReportingUrl)
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("ajaxSection", "overview-service-performance")
				.check(substring("Data table")))

			.exec(http("OverviewTaskEvents")
				.post(Environment.waLiveReportingUrl)
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("ajaxSection", "overview-task-events")
				.check(substring("Created, completed and cancelled tasks by service")))
		}

		.pause(Environment.constantthinkTime)

		.feed(serviceFeeder)
		.feed(regionFeeder)
		.feed(roleFeeder)

		.group("WALiveReporting_040_Overview_ApplyFilters") {
			exec(http("Overview")
				.post(Environment.waLiveReportingUrl)
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("applyFilters", "1")
				.check(substring("Tasks outstanding")))

			.exec(http("OverviewServicePerformance")
				.post(Environment.waLiveReportingUrl)
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("ajaxSection", "overview-service-performance")
				.check(substring("Open and assigned tasks by service")))

			.exec(http("OverTaskEvents")
				.post(Environment.waLiveReportingUrl)
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("ajaxSection", "overview-task-events")
				.check(substring("Date range from")))
		}

		.pause(Environment.constantthinkTime)

		.exec(_.setAll(
			"todayDate" -> DateUtils.getDateNow("dd-MM-yyyy"),
			"pastDate" -> DateUtils.getDatePastRandom("dd-MM-yyyy", minDays = 1, maxDays = 60)))

		// Created, completed and cancelled tasks date range search
		.group("WALiveReporting_050_Overview_TasksByService") {
			exec(http("OverviewTaskEvents")
				.post(Environment.waLiveReportingUrl)
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("eventsFrom", "#{pastDate}")
				.formParam("eventsTo", "#{todayDate}")
				.formParam("ajaxSection", "overview-task-events")
				.check(substring("Data table"))
				.check(substring("Download CSV")))
		}

		.pause(Environment.constantthinkTime)
	}

	val Outstanding = {

		group("WALiveReporting_060_Outstanding") {
			exec(http("TasksOutstanding")
				.get(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.check(substring("Details of outstanding tasks")))

			.exec(http("TasksOutstandingOpenTasksSummary")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "open-tasks-summary")
				.check(substring("Open tasks")))

			.exec(http("TasksOutstandingOpenTasksTable")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "open-tasks-table")
				.check(substring("Open tasks by created date with current assignment state")))

			.exec(http("TasksOutstandingWaitTimeTable")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "wait-time-table")
				.check(substring("Average wait time")))

			.exec(http("TasksOutstandingCriticalTasks")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "criticalTasks")
				.check(substring("Critical tasks")))

			.exec(http("TasksOutstandingTasksDue")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "tasks-due")
				.check(substring("Tasks due")))

			.exec(http("TasksOutstandingOpenTasksPriority")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "open-tasks-priority")
				.check(substring("Open tasks priority")))

			.exec(http("TasksOutstandingOpenByName")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "open-by-name")
				.check(substring("Open tasks by name")))

			.exec(http("TasksOutstandingOpenByRegionLocation")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "open-by-region-location")
				.check(substring("Tasks outstanding by region or location")))
		}

		.pause(Environment.constantthinkTime)

		.feed(serviceFeeder)
		.feed(regionFeeder)
		.feed(roleFeeder)

		.group("WALiveReporting_070_OutstandingApplyFilter") {
			exec(http("TasksOutstanding")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "shared-filters")
				.formParam("changedFilter", "service")
				.formParam("facetRefresh", "1")
				.check(substring("Details of outstanding tasks")))

			.exec(http("TasksOutstandingOpenTasksSummary")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "open-tasks-summary")
				.check(substring("Open tasks")))

			.exec(http("TasksOutstandingOpenTasksTable")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "open-tasks-table")
				.check(substring("Open tasks by created date with current assignment state")))

			.exec(http("TasksOutstandingWaitTimeTable")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "wait-time-table")
				.check(substring("Average wait time")))

			.exec(http("TasksOutstandingTasksDue")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "tasks-due")
				.check(substring("Tasks due")))

			.exec(http("TasksOutstandingCriticalTasks")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "criticalTasks")
				.check(substring("Critical tasks")))

			.exec(http("TasksOutstandingOpenTasksPriority")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "open-tasks-priority")
				.check(substring("Open tasks priority")))

			.exec(http("TasksOutstandingOpenByName")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "open-by-name")
				.check(substring("Open tasks by name")))

			.exec(http("TasksOutstandingOpenByRegionLocation")
				.post(Environment.waLiveReportingUrl + "/outstanding")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("ajaxSection", "open-by-region-location")
				.check(substring("Tasks outstanding by region or location")))
		}

		.pause(Environment.constantthinkTime)

	}

	val Completed = {

		group("WALiveReporting_080_Completed") {
			exec(http("TasksCompleted")
				.get(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.check(substring("Details of completed tasks")))

			.exec(http("TasksCompletedCompletedSummary")
				.post(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "completed-summary")
				.check(substring("Completed tasks (today)")))

			.exec(http("TasksCompletedCompletedTimeline")
				.post(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "completed-timeline")
				.check(substring("Completed tasks within the selected date range")))

			.exec(http("TasksCompletedCompletedByName")
				.post(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "completed-by-name")
				.check(substring("Completed tasks by name")))

			.exec(http("TasksCompletedCompletedProcessingHandlingTime")
				.post(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "completed-processing-handling-time")
				.check(substring("Processing and handling time")))

			.exec(http("TasksCompletedCompletedTaskAudit")
				.post(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "completed-task-audit")
				.check(substring("Task audit")))

			.exec(http("TasksCompletedCompletedByRegionLocation")
				.post(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "completed-by-region-location")
				.check(substring("Tasks completed by region or location")))
		}

		.pause(Environment.constantthinkTime)

		.feed(serviceFeeder)
		.feed(regionFeeder)
		.feed(roleFeeder)

		.group("WALiveReporting_090_Completed_ApplyFilter") {
			exec(http("TasksCompleted")
				.post(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "shared-filters")
				.formParam("changedFilter", "service")
				.formParam("facetRefresh", "1")
				.check(substring("Details of completed tasks")))

			.exec(http("TasksCompletedCompletedSummary")
				.post(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "completed-summary")
				.check(substring("Completed tasks (today)")))

			.exec(http("TasksCompletedCompletedTimeline")
				.post(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "completed-timeline")
				.check(substring("Completed tasks within the selected date range")))

			.exec(http("TasksCompletedCompletedByName")
				.post(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "completed-by-name")
				.check(substring("Completed tasks by name")))

			.exec(http("TasksCompletedCompletedProcessingHandlingTime")
				.post(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "completed-processing-handling-time")
				.check(substring("Processing and handling time")))

			.exec(http("TasksCompletedCompletedTaskAudit")
				.post(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "completed-task-audit")
				.check(substring("Task audit")))

			.exec(http("TasksCompletedCompletedByRegionLocation")
				.post(Environment.waLiveReportingUrl + "/completed")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "completed-by-region-location")
				.check(substring("Tasks completed by region or location")))
		}

		.pause(Environment.constantthinkTime)

	}

	val Users = {

		group("WALiveReporting_100_Users") {
			exec(http("Users")
				.get(Environment.waLiveReportingUrl + "/users")
				.headers(Headers.WALiveReportingHeader)
				.check(substring("Details of current and completed tasks for a specific user")))

			.exec(http("UsersUserOverviewAssigned")
				.post(Environment.waLiveReportingUrl + "/users")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("assignedSortBy", "createdDate")
				.formParam("assignedSortDir", "desc")
				.formParam("completedSortBy", "completedDate")
				.formParam("completedSortDir", "desc")
				.formParam("assignedPage", "1")
				.formParam("completedPage", "1")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "user-overview-assigned")
				.check(substring("Currently assigned tasks")))

			.exec(http("UsersUserOverviewCompletedOverview")
				.post(Environment.waLiveReportingUrl + "/users")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("assignedSortBy", "createdDate")
				.formParam("assignedSortDir", "desc")
				.formParam("completedSortBy", "completedDate")
				.formParam("completedSortDir", "desc")
				.formParam("assignedPage", "1")
				.formParam("completedPage", "1")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "user-overview-completed-overview")
				.check(substring("user-overview-completed")))

			.exec(http("UsersUserOverciewCompletedByTaskName")
				.post(Environment.waLiveReportingUrl + "/users")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("assignedSortBy", "createdDate")
				.formParam("assignedSortDir", "desc")
				.formParam("completedSortBy", "completedDate")
				.formParam("completedSortDir", "desc")
				.formParam("assignedPage", "1")
				.formParam("completedPage", "1")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "user-overview-completed-by-task-name")
				.check(substring("Completed tasks by task name")))
		}

		.pause(Environment.constantthinkTime)

		.feed(serviceFeeder)
		.feed(regionFeeder)
		.feed(roleFeeder)

		.group("WALiveReporting_110_Users_ApplyFilter") {
			exec(http("Users")
				.post(Environment.waLiveReportingUrl + "/users")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("assignedSortBy", "createdDate")
				.formParam("assignedSortDir", "desc")
				.formParam("completedSortBy", "completedDate")
				.formParam("completedSortDir", "desc")
				.formParam("assignedPage", "1")
				.formParam("completedPage", "1")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "shared-filters")
				.formParam("changedFilter", "service")
				.formParam("facetRefresh", "1")
				.check(substring("Currently assigned tasks")))

			.exec(http("UsersUserOverviewAssigned")
				.post(Environment.waLiveReportingUrl + "/users")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("assignedSortBy", "createdDate")
				.formParam("assignedSortDir", "desc")
				.formParam("completedSortBy", "completedDate")
				.formParam("completedSortDir", "desc")
				.formParam("assignedPage", "1")
				.formParam("completedPage", "1")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "user-overview-assigned")
				.check(substring("Currently assigned tasks")))

			.exec(http("UsersUserOverviewCompletedSummary")
				.post(Environment.waLiveReportingUrl + "/users")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("assignedSortBy", "createdDate")
				.formParam("assignedSortDir", "desc")
				.formParam("completedSortBy", "completedDate")
				.formParam("completedSortDir", "desc")
				.formParam("assignedPage", "1")
				.formParam("completedPage", "1")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "user-overview-completed-overview")
				.check(substring("user-overview-completed")))

			.exec(http("UserUserOverviewCompletedByTaskName")
				.post(Environment.waLiveReportingUrl + "/users")
				.headers(Headers.WALiveReportingHeader)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("service", "#{service}")
				.formParam("region", "#{region}")
				.formParam("roleCategory", "#{role}")
				.formParam("assignedSortBy", "createdDate")
				.formParam("assignedSortDir", "desc")
				.formParam("completedSortBy", "completedDate")
				.formParam("completedSortDir", "desc")
				.formParam("assignedPage", "1")
				.formParam("completedPage", "1")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("ajaxSection", "user-overview-completed-by-task-name")
				.check(substring("Completed tasks by task name")))
			}

		.pause(Environment.constantthinkTime)

	}

	val Logout =

		exec(http("WALiveReporting_120_Logout")
			.get(Environment.waLiveReportingUrl + "/logout")
			.headers(Headers.WALiveReportingHeader)
			.check(substring("Enter your email address")))
}