package scenarios.common.wa

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import utils.{Environment, Headers}
import xui._

object LiveReportingJourney {

	val HomePage = {

		exec(http("request_0")
			.get(Environment.waLiveReportingUrl)
			.headers(Headers.WALiveReportingHeader)
			.check(css("input[name='_csrf']", "value").saveAs("csrf"))
			.check(headerRegex("Set-Cookie", "x-csrf-token=(.+?);").saveAs("snapshotToken")))
	}

	.pause(Environment.constantthinkTime)

	val Login = {

		exec(http("request_3")
			.post(Environment.hmctsAccessUrl + "/enter-email")
			.headers(Headers.WALiveReportingHeader)
			.formParam("email", "perf_wa_reporting_001@gmail.com")
			.formParam("_csrf", "#{csrf}"))

		.exec(http("request_6")
			.post(Environment.hmctsAccessUrl + "/enter-password")
			.headers(Headers.WALiveReportingHeader)
			.formParam("action", "_submit")
			.formParam("password", "Password12")
			.formParam("_csrf", "#{csrf}")
			.check(css("input[name='_csrf']", "value").saveAs("csrf")))
	}

	.pause(Environment.constantthinkTime)

	val Overview = {

		exec(http("request_9")
			.post(Environment.waLiveReportingUrl)
			.headers(Headers.WALiveReportingHeader)
			.formParam("_csrf", "#{csrf}")
			.formParam("snapshotToken", "#{snapshotToken}")
			.formParam("ajaxSection", "overview-service-performance"))

		.exec(http("request_10")
			.post(Environment.waLiveReportingUrl)
			.headers(Headers.WALiveReportingHeader)
			.formParam("_csrf", "#{csrf}")
			.formParam("snapshotToken", "#{snapshotToken}")
			.formParam("ajaxSection", "overview-task-events"))

		.pause(Environment.constantthinkTime)

		//Select filters from dropdown
		.exec(http("request_11")
			.post(Environment.waLiveReportingUrl)
			.headers(Headers.WALiveReportingHeader)
			.formParam("_csrf", "#{csrf}")
			.formParam("snapshotToken", "#{snapshotToken}")
			.formParam("service", "Civil")
			.formParam("service", "Employment")
			.formParam("ajaxSection", "shared-filters")
			.formParam("changedFilter", "service")
			.formParam("facetRefresh", "1"))

		.exec(http("request_12")
			.post(Environment.waLiveReportingUrl)
			.headers(Headers.WALiveReportingHeader)
			.formParam("_csrf", "#{csrf}")
			.formParam("snapshotToken", "#{snapshotToken}")
			.formParam("service", "Civil")
			.formParam("service", "Employment")
			.formParam("applyFilters", "1"))

		//Apply filter
		.exec(http("request_15")
			.post(Environment.waLiveReportingUrl)
			.headers(Headers.WALiveReportingHeader)
			.formParam("_csrf", "#{csrf}")
			.formParam("snapshotToken", "#{snapshotToken}")
			.formParam("service", "Civil")
			.formParam("service", "Employment")
			.formParam("ajaxSection", "overview-service-performance"))

		.exec(http("request_16")
			.post(Environment.waLiveReportingUrl)
			.headers(Headers.WALiveReportingHeader)
			.formParam("_csrf", "#{csrf}")
			.formParam("snapshotToken", "#{snapshotToken}")
			.formParam("service", "Civil")
			.formParam("service", "Employment")
			.formParam("ajaxSection", "overview-task-events"))

		.pause(Environment.constantthinkTime)
	}

		/*
		.pause(16)
		.exec(http("request_17")
			.post("/")
			.headers(headers_9)
			.formParam("_csrf", "#{csrf}")
			.formParam("snapshotToken", "#{snapshotToken}")
			.formParam("service", "Civil")
			.formParam("eventsFrom", "1/6/2026")
			.formParam("eventsTo", "26/06/2026")
			.formParam("ajaxSection", "overview-task-events"))
		.pause(5)
		.exec(http("request_18")
			.get("/assets/manifest.json")
			.headers(headers_7)
			.resources(http("request_19")
				.get("/outstanding")
				.headers(headers_19),
				http("request_20")
					.get("/assets/images/govuk-crest.svg")
					.headers(headers_8),
				http("request_21")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Civil")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "open-tasks-summary"),
				http("request_22")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Civil")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "wait-time-table"),
				http("request_23")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Civil")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "criticalTasks"),
				http("request_24")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Civil")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "tasks-due"),
				http("request_25")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Civil")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "open-tasks-priority"),
				http("request_26")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Civil")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "open-by-name"),
				http("request_27")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Civil")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "open-by-region-location")))
		.pause(3)
		.exec(http("request_28")
			.post("/outstanding")
			.headers(headers_9)
			.formParam("_csrf", "#{csrf}")
			.formParam("snapshotToken", "#{snapshotToken}")
			.formParam("criticalTasksSortBy", "dueDate")
			.formParam("criticalTasksSortDir", "asc")
			.formParam("criticalTasksPage", "1")
			.formParam("ajaxSection", "shared-filters")
			.formParam("changedFilter", "service")
			.formParam("facetRefresh", "1")
			.resources(http("request_29")
				.post("/outstanding")
				.headers(headers_12)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("criticalTasksSortBy", "dueDate")
				.formParam("criticalTasksSortDir", "asc")
				.formParam("criticalTasksPage", "1")
				.formParam("applyFilters", "1"),
				http("request_30")
					.get("/assets/manifest.json")
					.headers(headers_7),
				http("request_31")
					.get("/assets/images/govuk-crest.svg")
					.headers(headers_8),
				http("request_32")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "open-tasks-summary"),
				http("request_33")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "open-tasks-table"),
				http("request_34")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "wait-time-table"),
				http("request_35")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "tasks-due"),
				http("request_36")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "criticalTasks"),
				http("request_37")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "open-tasks-priority"),
				http("request_38")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "open-by-name"),
				http("request_39")
					.post("/outstanding")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("criticalTasksSortBy", "dueDate")
					.formParam("criticalTasksSortDir", "asc")
					.formParam("criticalTasksPage", "1")
					.formParam("ajaxSection", "open-by-region-location")))
		.pause(3)
		.exec(http("request_40")
			.get("/completed")
			.headers(headers_19)
			.resources(http("request_41")
				.get("/assets/manifest.json")
				.headers(headers_7),
				http("request_42")
					.get("/assets/images/govuk-crest.svg")
					.headers(headers_8),
				http("request_43")
					.post("/completed")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "completed-summary"),
				http("request_44")
					.post("/completed")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "completed-timeline"),
				http("request_45")
					.post("/completed")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "completed-by-name"),
				http("request_46")
					.post("/completed")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "completed-processing-handling-time"),
				http("request_47")
					.post("/completed")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "completed-task-audit"),
				http("request_48")
					.post("/completed")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "completed-by-region-location")))
		.pause(2)
		.exec(http("request_49")
			.post("/completed")
			.headers(headers_9)
			.formParam("_csrf", "#{csrf}")
			.formParam("snapshotToken", "#{snapshotToken}")
			.formParam("service", "Employment")
			.formParam("completedFrom", "")
			.formParam("completedTo", "")
			.formParam("ajaxSection", "shared-filters")
			.formParam("changedFilter", "service")
			.formParam("facetRefresh", "1")
			.resources(http("request_50")
				.post("/completed")
				.headers(headers_12)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("service", "Employment")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("applyFilters", "1"),
				http("request_51")
					.get("/assets/manifest.json")
					.headers(headers_7),
				http("request_52")
					.get("/assets/images/govuk-crest.svg")
					.headers(headers_8),
				http("request_53")
					.post("/completed")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Employment")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "completed-summary"),
				http("request_54")
					.post("/completed")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Employment")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "completed-timeline"),
				http("request_55")
					.post("/completed")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Employment")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "completed-by-name"),
				http("request_56")
					.post("/completed")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Employment")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "completed-processing-handling-time"),
				http("request_57")
					.post("/completed")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Employment")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "completed-task-audit"),
				http("request_58")
					.post("/completed")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Employment")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "completed-by-region-location")))
		.pause(10)
		.exec(http("request_59")
			.get("/users")
			.headers(headers_19)
			.resources(http("request_60")
				.get("/assets/manifest.json")
				.headers(headers_7),
				http("request_61")
					.get("/assets/images/govuk-crest.svg")
					.headers(headers_8),
				http("request_62")
					.post("/users")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Employment")
					.formParam("assignedSortBy", "createdDate")
					.formParam("assignedSortDir", "desc")
					.formParam("completedSortBy", "completedDate")
					.formParam("completedSortDir", "desc")
					.formParam("assignedPage", "1")
					.formParam("completedPage", "1")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "user-overview-assigned"),
				http("request_63")
					.post("/users")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Employment")
					.formParam("assignedSortBy", "createdDate")
					.formParam("assignedSortDir", "desc")
					.formParam("completedSortBy", "completedDate")
					.formParam("completedSortDir", "desc")
					.formParam("assignedPage", "1")
					.formParam("completedPage", "1")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "user-overview-completed-overview"),
				http("request_64")
					.post("/users")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("service", "Employment")
					.formParam("assignedSortBy", "createdDate")
					.formParam("assignedSortDir", "desc")
					.formParam("completedSortBy", "completedDate")
					.formParam("completedSortDir", "desc")
					.formParam("assignedPage", "1")
					.formParam("completedPage", "1")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "user-overview-completed-by-task-name")))
		.pause(3)
		.exec(http("request_65")
			.post("/users")
			.headers(headers_9)
			.formParam("_csrf", "#{csrf}")
			.formParam("snapshotToken", "#{snapshotToken}")
			.formParam("service", "Civil")
			.formParam("service", "Employment")
			.formParam("service", "EMPLOYMENT")
			.formParam("service", "Immigration and Asylum")
			.formParam("service", "Private Law")
			.formParam("service", "Public Law")
			.formParam("service", "Special Tribunals CIC")
			.formParam("service", "SSCS")
			.formParam("service", "ST_CIC")
			.formParam("service", "WA")
			.formParam("assignedSortBy", "createdDate")
			.formParam("assignedSortDir", "desc")
			.formParam("completedSortBy", "completedDate")
			.formParam("completedSortDir", "desc")
			.formParam("assignedPage", "1")
			.formParam("completedPage", "1")
			.formParam("completedFrom", "")
			.formParam("completedTo", "")
			.formParam("ajaxSection", "shared-filters")
			.formParam("changedFilter", "service")
			.formParam("facetRefresh", "1")
			.resources(http("request_66")
				.post("/users")
				.headers(headers_12)
				.formParam("_csrf", "#{csrf}")
				.formParam("snapshotToken", "#{snapshotToken}")
				.formParam("assignedSortBy", "createdDate")
				.formParam("assignedSortDir", "desc")
				.formParam("completedSortBy", "completedDate")
				.formParam("completedSortDir", "desc")
				.formParam("assignedPage", "1")
				.formParam("completedPage", "1")
				.formParam("completedFrom", "")
				.formParam("completedTo", "")
				.formParam("applyFilters", "1"),
				http("request_67")
					.get("/assets/manifest.json")
					.headers(headers_7),
				http("request_68")
					.get("/assets/images/govuk-crest.svg")
					.headers(headers_8),
				http("request_69")
					.post("/users")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("assignedSortBy", "createdDate")
					.formParam("assignedSortDir", "desc")
					.formParam("completedSortBy", "completedDate")
					.formParam("completedSortDir", "desc")
					.formParam("assignedPage", "1")
					.formParam("completedPage", "1")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "user-overview-assigned"),
				http("request_70")
					.post("/users")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("assignedSortBy", "createdDate")
					.formParam("assignedSortDir", "desc")
					.formParam("completedSortBy", "completedDate")
					.formParam("completedSortDir", "desc")
					.formParam("assignedPage", "1")
					.formParam("completedPage", "1")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "user-overview-completed-overview"),
				http("request_71")
					.post("/users")
					.headers(headers_9)
					.formParam("_csrf", "#{csrf}")
					.formParam("snapshotToken", "#{snapshotToken}")
					.formParam("assignedSortBy", "createdDate")
					.formParam("assignedSortDir", "desc")
					.formParam("completedSortBy", "completedDate")
					.formParam("completedSortDir", "desc")
					.formParam("assignedPage", "1")
					.formParam("completedPage", "1")
					.formParam("completedFrom", "")
					.formParam("completedTo", "")
					.formParam("ajaxSection", "user-overview-completed-by-task-name")))
		.pause(8)
		.exec(http("request_72")
			.get("/logout")
			.headers(headers_19)
			.resources(http("request_73")
				.get(Environment.hmctsAccessUrl + "/assets/images/govuk-crest.svg")
				.headers(headers_73),
				http("request_74")
					.get(Environment.hmctsAccessUrl + "/assets/manifest.json")
					.headers(headers_2)))


		 */

}
